version: "3"
services:
  dockerApp:
    container_name: expresstest
    image: wayrex/expresstest
    restart: always
    env_file: .env
    environment:
      - HOST=mongo
    build: .
    ports:
      - 80:8080
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    env_file: .env
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DATABASE_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DATABASE_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$DATABASE
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - MONGO_PORT=$DATABASE_PORT
    volumes:
      - data:/data/db
      - ./docker_scripts/:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
volumes:
  data: